name: ODK Dashboard Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # ODK secrets
      ODK_PROJECT_ID: ${{ secrets.ODK_PROJECT_ID }}
      ODK_URL: ${{ secrets.ODK_URL }}
      ODK_USERNAME: ${{ secrets.ODK_USERNAME }}
      ODK_PASSWORD: ${{ secrets.ODK_PASSWORD }}

      # Custom secrets if needed
      #API_TOKEN: ${{ secrets.API_TOKEN }}
      #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert ipykernel jupyter
          pip install git+https://${GITHUB_TOKEN}@github.com/myorg/my-secret-utils.git

      - name: Install Jupyter Kernel (User Scope)
        run: |
          python -m ipykernel install --user --name python3 --display-name "Python 3"

      - name: Check available Jupyter kernels
        run: |
          jupyter kernelspec list

      - name: Run ODK client script
        run: |
          python your_script.py

      - name: Execute notebook
        run: |
          jupyter nbconvert --to html --execute --no-input rp_dashboard.ipynb --output index.html

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add index.html
          git commit -m "Update dashboard"
          git push
